"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
from decouple import config 
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',

    # Third-party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'allauth.socialaccount.providers.openid', 
    'allauth.socialaccount.providers.steam',

    'vault',  # App do projeto
]

SITE_ID = 1 # Necessário para allauth

# Configuração Allauth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Adapter customizado que vamos criar
SOCIALACCOUNT_ADAPTER = 'vault.adapters.AlkahestSocialAdapter'

# Configuração Steam (Sem e-mail verification forçado pois Steam não retorna e-mail confiavelmente as vezes)
ACCOUNT_EMAIL_VERIFICATION = "none" 
ACCOUNT_UNIQUE_EMAIL = True
LOGIN_REDIRECT_URL = 'dashboard'

# Provider Configuration
SOCIALACCOUNT_PROVIDERS = {
    'steam': {
        'APP': {
            'client_id': '12345', # Não usado pela Steam, mas requerido pelo formato
            'secret': config('STEAM_API_KEY'), 
            'key': ''
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # --- NOVO MIDDLEWARE DO ALLAUTH (Obrigatório) ---
    'allauth.account.middleware.AccountMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Tenta pegar do .env, se falhar, vai pro SQLite
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600,
        # REMOVIDO: ssl_require=True (Deixe a URL controlar isso)
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'library' # Para onde vai depois de logar
LOGOUT_REDIRECT_URL = 'login'  # Para onde vai depois de deslogar

# URL para referenciar arquivos estáticos (CSS, JavaScript, Imagens)
# Exemplo de uso no template: {% static 'vault/images/logo_white.svg' %}
STATIC_URL = '/static/'

# Diretórios adicionais onde o Django vai procurar por arquivos estáticos
# Adicionamos a pasta 'static' que criamos na raiz do projeto.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ==========================================
# CACHE & REDIS CONFIGURATION
# ==========================================
# Se não tiver Redis local rodando, vai falhar. Garanta que o serviço está up.
# Em produção, usaremos a variável REDIS_URL.
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Ignora erros de conexão para não derrubar o site se o cache cair
            'IGNORE_EXCEPTIONS': True, 
        }
    }
}

# ==========================================
# CELERY CONFIGURATION
# ==========================================
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Usa o mesmo do Django

# Retry de conexão na inicialização do worker
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True