# Generated by Django 6.0.1 on 2026-01-12 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('igdb_id', models.BigIntegerField(help_text='ID único do jogo no IGDB', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genres', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('external_title', models.CharField(max_length=255)),
                ('master_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='vault.mastergame')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.platform')),
            ],
            options={
                'unique_together': {('platform', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('xp_value', models.IntegerField(default=0)),
                ('platform_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='vault.platformgame')),
            ],
        ),
        migrations.CreateModel(
            name='UserLibraryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('playing', 'Jogando'), ('completed', 'Zerado'), ('dropped', 'Largado')], default='backlog', max_length=20)),
                ('playtime_minutes', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True)),
                ('platform_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.platformgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
