# Generated by Django 6.0.1 on 2026-01-28 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('igdb_id', models.BigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Main Game'), (1, 'DLC/Addon'), (2, 'Expansion'), (3, 'Bundle'), (4, 'Standalone Expansion'), (5, 'Mod'), (6, 'Episode'), (7, 'Season'), (8, 'Remake'), (9, 'Remaster'), (10, 'Expanded Game'), (11, 'Port'), (12, 'Fork'), (13, 'Pack'), (14, 'Update')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Released'), (2, 'Alpha'), (3, 'Beta'), (4, 'Early Access'), (5, 'Offline'), (6, 'Cancelled'), (7, 'Rumored'), (8, 'Delisted')], default=0)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('background_url', models.URLField(blank=True, null=True)),
                ('artworks', models.JSONField(blank=True, default=list)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('storyline', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('developers', models.JSONField(blank=True, default=list)),
                ('publishers', models.JSONField(blank=True, default=list)),
                ('game_engines', models.JSONField(blank=True, default=list)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('game_modes', models.JSONField(blank=True, default=list)),
                ('player_perspectives', models.JSONField(blank=True, default=list)),
                ('collection', models.CharField(blank=True, max_length=255, null=True)),
                ('franchises', models.JSONField(blank=True, default=list)),
                ('similar_games', models.JSONField(blank=True, default=list)),
                ('dlcs', models.JSONField(blank=True, default=list)),
                ('supported_languages', models.JSONField(blank=True, default=dict)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vault.mastergame')),
            ],
        ),
        migrations.CreateModel(
            name='GameTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_achievement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(max_length=280)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL)),
                ('master_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='vault.mastergame')),
            ],
        ),
        migrations.CreateModel(
            name='GameListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('game_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vault.gamelist')),
                ('master_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.mastergame')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlatformGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('external_title', models.CharField(max_length=255)),
                ('master_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='vault.mastergame')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.platform')),
            ],
            options={
                'unique_together': {('platform', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('xp_value', models.IntegerField(default=0)),
                ('platform_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='vault.platformgame')),
            ],
        ),
        migrations.CreateModel(
            name='UserLibraryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('playing', 'Jogando'), ('completed', 'Zerado'), ('dropped', 'Largado')], db_index=True, default='backlog', max_length=20)),
                ('playtime_minutes', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(blank=True, null=True)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='BRL', max_length=3)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('platform_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.platformgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(help_text='Escreva usando Markdown')),
                ('text_html', models.TextField(blank=True, editable=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('is_recommended', models.BooleanField(blank=True, null=True)),
                ('playtime_at_review', models.IntegerField(null=True)),
                ('contains_spoilers', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_replay', models.BooleanField(default=False)),
                ('language', models.CharField(default='pt-br', max_length=10)),
                ('achievement_percent_snapshot', models.FloatField(default=0.0)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vault.userlibraryentry')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('stat_volume', models.IntegerField(default=0)),
                ('stat_skill', models.IntegerField(default=0)),
                ('stat_variety', models.IntegerField(default=0)),
                ('stat_social', models.IntegerField(default=0)),
                ('stat_speed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vault.gametip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tip')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['follower'], name='vault_userf_followe_3b58ed_idx'), models.Index(fields=['target'], name='vault_userf_target__7c3746_idx')],
                'unique_together': {('follower', 'target')},
            },
        ),
    ]
