# Generated by Django 6.0.1 on 2026-01-28 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('igdb_category_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameStoreLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, help_text='AppID da Steam, ConceptID da PSN, etc', max_length=255)),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_links', to='vault.mastergame')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_links', to='vault.store')),
            ],
            options={
                'ordering': ['last_checked_at'],
                'unique_together': {('store', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_regular', models.DecimalField(decimal_places=2, help_text='Preço cheio sem desconto', max_digits=10)),
                ('price_final', models.DecimalField(decimal_places=2, help_text='Preço final para o consumidor (com desconto)', max_digits=10)),
                ('currency', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro')], db_index=True, default='BRL', max_length=3)),
                ('is_free', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('is_subscription', models.BooleanField(default=False, help_text='Ex: GamePass, PS Plus Extra')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='vault.gamestorelink')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['link', 'timestamp'], name='vault_price_link_id_7bf90c_idx')],
            },
        ),
    ]
