# Generated by Django 6.0.1 on 2026-01-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibraryentry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlibraryentry',
            name='is_recommended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlibraryentry',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlibraryentry',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
