# Generated by Django 6.0.1 on 2026-01-28 21:45
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_store_gamestorelink_pricehistory'),
    ]

    operations = [
    ]
