# Generated by Django 6.0.1 on 2026-02-01 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_review_rating_alter_userlibraryentry_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibraryentry',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, help_text='Armazenado como 0-100', null=True),
        ),
        migrations.CreateModel(
            name='ProfileImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='backloggd', max_length=50)),
                ('target_username', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Na Fila'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falha')], default='pending', max_length=20)),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('log_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
