# Generated by Django 6.0.1 on 2026-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_alter_userlibraryentry_rating_profileimportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, help_text='Quem recebeu este código?', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('follow', 'New Follower'), ('like', 'Like'), ('price', 'Price Alert'), ('release', 'New Release')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileimportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
