# Generated by Django 6.0.1 on 2026-01-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_gamelist_gamelistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='achievement_percent_snapshot',
            field=models.FloatField(default=0.0, help_text='% de conquistas no momento da review'),
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(blank=True, help_text='Ex: horror, indie, masterpiece', max_length=255),
        ),
    ]
