# Generated by Django 6.0.1 on 2026-01-24 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_review_achievement_percent_snapshot_review_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_html',
            field=models.TextField(blank=True, editable=False, help_text='HTML gerado automaticamente'),
        ),
        migrations.AlterField(
            model_name='review',
            name='achievement_percent_snapshot',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='playtime_at_review',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Escreva usando Markdown'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('stat_volume', models.IntegerField(default=0)),
                ('stat_skill', models.IntegerField(default=0)),
                ('stat_variety', models.IntegerField(default=0)),
                ('stat_social', models.IntegerField(default=0)),
                ('stat_speed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
