# Generated by Django 6.0.1 on 2026-01-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_review_text_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='platform_played',
        ),
        migrations.AddField(
            model_name='review',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='userlibraryentry',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
