# Generated by Django 6.0.1 on 2026-01-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_remove_review_platform_played_review_is_recommended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_recommended',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
