# Generated by Django 6.0.1 on 2026-01-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_alter_review_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastergame',
            name='igdb_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mastergame',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userlibraryentry',
            name='last_played',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlibraryentry',
            name='rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlibraryentry',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('playing', 'Jogando'), ('completed', 'Zerado'), ('dropped', 'Largado')], db_index=True, default='backlog', max_length=20),
        ),
    ]
